# Generated by Django 4.2.1 on 2023-09-11 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affaire',
            fields=[
                ('idAffaire', models.AutoField(primary_key=True, serialize=False)),
                ('energie', models.CharField(choices=[('electricité', 'Elec'), ('gaz', 'Gaz')], max_length=15, null=True)),
                ('remarque', models.CharField(max_length=300, null=True)),
                ('numAFF', models.CharField(max_length=20)),
                ('numOET', models.CharField(max_length=10, null=True)),
                ('detailObjet', models.CharField(max_length=150)),
                ('adresse', models.CharField(max_length=150, null=True)),
                ('commune', models.CharField(default=None, max_length=40, null=True)),
                ('montant', models.FloatField(null=True)),
                ('dateAriveDRS', models.DateField(default=None, null=True)),
                ('dateEnvoiAPC', models.DateField(default=None, null=True)),
                ('dateEnvoiADCAPC', models.DateField(default=None, null=True)),
                ('sitAff', models.CharField(max_length=180, null=True)),
                ('numODS', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChemiseDeTravaux',
            fields=[
                ('idChemise', models.AutoField(primary_key=True, serialize=False)),
                ('DRCHT', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idClient', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('idContrat', models.AutoField(primary_key=True, serialize=False)),
                ('numContrat', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('idEntreprise', models.AutoField(primary_key=True, serialize=False)),
                ('raisonSocial', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Autorisation',
            fields=[
                ('idAutorisation', models.AutoField(primary_key=True, serialize=False)),
                ('numAutor', models.CharField(max_length=60, null=True)),
                ('dateAutor', models.DateField(null=True)),
                ('numDemAutor', models.CharField(max_length=60, null=True)),
                ('dateDEmendaAuto', models.DateField(null=True)),
                ('affaire', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.affaire')),
            ],
        ),
        migrations.AddField(
            model_name='affaire',
            name='client',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.client'),
        ),
        migrations.AddField(
            model_name='affaire',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.contrat'),
        ),
        migrations.AddField(
            model_name='affaire',
            name='entreprise',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.entreprise'),
        ),
    ]
