# Generated by Django 4.2.1 on 2023-09-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_affaire_contrat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affaire',
            name='montant',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
