# Generated by Django 4.2.1 on 2023-09-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_affaire_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affaire',
            name='detailObjet',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
