# Generated by Django 4.2.1 on 2023-09-25 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_contrat_numcontrat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemisedetravaux',
            name='AC',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='chemisedetravaux',
            name='BERTS',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='chemisedetravaux',
            name='BRT_2F',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='chemisedetravaux',
            name='BRT_4F',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='chemisedetravaux',
            name='BTA',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='chemisedetravaux',
            name='BTS',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='chemisedetravaux',
            name='CM',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='chemisedetravaux',
            name='EQUIP',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='chemisedetravaux',
            name='MTA',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='chemisedetravaux',
            name='MTS',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='chemisedetravaux',
            name='PE125',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='chemisedetravaux',
            name='PE200',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='chemisedetravaux',
            name='PE250',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='chemisedetravaux',
            name='PE40',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='chemisedetravaux',
            name='PE63',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='chemisedetravaux',
            name='PUISS',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='chemisedetravaux',
            name='TYPE',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='chemisedetravaux',
            name='affaire',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.affaire'),
        ),
        migrations.AlterField(
            model_name='affaire',
            name='energie',
            field=models.CharField(choices=[('ELEC', 'Elec'), ('GAZ', 'Gaz')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='chemisedetravaux',
            name='DRCHT',
            field=models.DateField(null=True),
        ),
    ]
