# Generated by Django 4.2.1 on 2023-09-26 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_chemisedetravaux_ac_chemisedetravaux_berts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chemisedetravaux',
            old_name='BERTS',
            new_name='BRTS',
        ),
    ]
