# Generated by Django 4.2.1 on 2023-10-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affaire',
            name='numOET',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
