# Generated by Django 4.2.1 on 2023-10-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_affaire_numoet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affaire',
            name='numOET',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
