# Generated by Django 4.2.1 on 2023-10-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_affaire_numoet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affaire',
            name='detailObjet',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
