# Generated by Django 4.2.1 on 2023-10-20 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_customuser_delete_customusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
